apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storefront-operator
  template:
    metadata:
      labels:
        name: storefront-operator
    spec:
      serviceAccountName: storefront-operator
      containers:
        - name: storefront-operator
          image: quay.io/eochieng/storefront-operator:v0.0.1
          command:
          - storefront-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "storefront-operator"
